all:
	cd evtxdump; $(MAKE) all
	#cd evtxmon; $(MAKE) all

install:
	cd evtxdump; $(MAKE) install
	#cd evtxmon; $(MAKE) install

linux:
	cd evtxdump; $(MAKE) linux
	#cd evtxmon; $(MAKE) linux

windows:
	cd evtxdump; $(MAKE) windows
	#cd evtxmon; $(MAKE) windows

darwin:
	cd evtxdump; $(MAKE) darwin
	#cd evtxmon; $(MAKE) darwin

clean:
	cd evtxdump; $(MAKE) clean
	#cd evtxmon; $(MAKE) clean
